#@data/values
---
port: 3000

env:
  - name: PORT
    value: "3000"
  - name: TZ
    value: America/Sao_Paulo

ingress:
  enable: true
  className: nginx
  domain: andreb.dev

deployment:
  replicas: 1
