name: pipeline

on: 
  push:
  deployment:
  release:
    types: [created]
  pull_request:
    types: [opened, reopened]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        default: 'dev'
        options:
        - dev
        - stg
        - prod
        
jobs:

  SVC:
    uses:  andrebrito16/iac-github-actions/.github/workflows/svc.yml@fix/push-go-image
    secrets: inherit
    with:
      mainBranch: main
      platforms: linux/amd64
      environmentsAsNamespaces: true